// HT45F75.h
//	This file contains the definition of registers for
//		Holtek HT45F75 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.6, 4
// Do not modify manually.

#ifndef _HT45F75_H_
#define _HT45F75_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __mp00 : 1;
	unsigned char __mp01 : 1;
	unsigned char __mp02 : 1;
	unsigned char __mp03 : 1;
	unsigned char __mp04 : 1;
	unsigned char __mp05 : 1;
	unsigned char __mp06 : 1;
	unsigned char __mp07 : 1;
} __mp0_bits;

typedef union {
	__mp0_bits bits;
	__sfr_byte byte;
} __mp0_type;

typedef struct {
	unsigned char __mp1l0 : 1;
	unsigned char __mp1l1 : 1;
	unsigned char __mp1l2 : 1;
	unsigned char __mp1l3 : 1;
	unsigned char __mp1l4 : 1;
	unsigned char __mp1l5 : 1;
	unsigned char __mp1l6 : 1;
	unsigned char __mp1l7 : 1;
} __mp1l_bits;

typedef union {
	__mp1l_bits bits;
	__sfr_byte byte;
} __mp1l_type;

typedef struct {
	unsigned char __mp1h0 : 1;
	unsigned char __mp1h1 : 1;
	unsigned char __mp1h2 : 1;
	unsigned char __mp1h3 : 1;
	unsigned char __mp1h4 : 1;
	unsigned char __mp1h5 : 1;
	unsigned char __mp1h6 : 1;
	unsigned char __mp1h7 : 1;
} __mp1h_bits;

typedef union {
	__mp1h_bits bits;
	__sfr_byte byte;
} __mp1h_type;

typedef struct {
	unsigned char __acc0 : 1;
	unsigned char __acc1 : 1;
	unsigned char __acc2 : 1;
	unsigned char __acc3 : 1;
	unsigned char __acc4 : 1;
	unsigned char __acc5 : 1;
	unsigned char __acc6 : 1;
	unsigned char __acc7 : 1;
} __acc_bits;

typedef union {
	__acc_bits bits;
	__sfr_byte byte;
} __acc_type;

typedef struct {
	unsigned char __pcl0 : 1;
	unsigned char __pcl1 : 1;
	unsigned char __pcl2 : 1;
	unsigned char __pcl3 : 1;
	unsigned char __pcl4 : 1;
	unsigned char __pcl5 : 1;
	unsigned char __pcl6 : 1;
	unsigned char __pcl7 : 1;
} __pcl_bits;

typedef union {
	__pcl_bits bits;
	__sfr_byte byte;
} __pcl_type;

typedef struct {
	unsigned char __tblp0 : 1;
	unsigned char __tblp1 : 1;
	unsigned char __tblp2 : 1;
	unsigned char __tblp3 : 1;
	unsigned char __tblp4 : 1;
	unsigned char __tblp5 : 1;
	unsigned char __tblp6 : 1;
	unsigned char __tblp7 : 1;
} __tblp_bits;

typedef union {
	__tblp_bits bits;
	__sfr_byte byte;
} __tblp_type;

typedef struct {
	unsigned char __tblh0 : 1;
	unsigned char __tblh1 : 1;
	unsigned char __tblh2 : 1;
	unsigned char __tblh3 : 1;
	unsigned char __tblh4 : 1;
	unsigned char __tblh5 : 1;
	unsigned char __tblh6 : 1;
	unsigned char __tblh7 : 1;
} __tblh_bits;

typedef union {
	__tblh_bits bits;
	__sfr_byte byte;
} __tblh_type;

typedef struct {
	unsigned char __tbhp0 : 1;
	unsigned char __tbhp1 : 1;
	unsigned char __tbhp2 : 1;
	unsigned char __tbhp3 : 1;
	unsigned char : 4;
} __tbhp_bits;

typedef union {
	__tbhp_bits bits;
	__sfr_byte byte;
} __tbhp_type;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __mp2l0 : 1;
	unsigned char __mp2l1 : 1;
	unsigned char __mp2l2 : 1;
	unsigned char __mp2l3 : 1;
	unsigned char __mp2l4 : 1;
	unsigned char __mp2l5 : 1;
	unsigned char __mp2l6 : 1;
	unsigned char __mp2l7 : 1;
} __mp2l_bits;

typedef union {
	__mp2l_bits bits;
	__sfr_byte byte;
} __mp2l_type;

typedef struct {
	unsigned char __mp2h0 : 1;
	unsigned char __mp2h1 : 1;
	unsigned char __mp2h2 : 1;
	unsigned char __mp2h3 : 1;
	unsigned char __mp2h4 : 1;
	unsigned char __mp2h5 : 1;
	unsigned char __mp2h6 : 1;
	unsigned char __mp2h7 : 1;
} __mp2h_bits;

typedef union {
	__mp2h_bits bits;
	__sfr_byte byte;
} __mp2h_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __mf0e : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char __mf0f : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __ade : 1;
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __mf1e : 1;
	unsigned char __adf : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __mf1f : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __mf2e : 1;
	unsigned char __mf3e : 1;
	unsigned char : 2;
	unsigned char __mf2f : 1;
	unsigned char __mf3f : 1;
	unsigned char : 2;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __t0pe : 1;
	unsigned char __t0ae : 1;
	unsigned char : 2;
	unsigned char __t0pf : 1;
	unsigned char __t0af : 1;
	unsigned char : 2;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char __sie : 1;
	unsigned char __uie : 1;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char __sif : 1;
	unsigned char __uif : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __t1pe : 1;
	unsigned char __t1ae : 1;
	unsigned char : 1;
	unsigned char __i2ctoi : 1;
	unsigned char __t1pf : 1;
	unsigned char __t1af : 1;
	unsigned char : 1;
	unsigned char __i2ctof : 1;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __t2pe : 1;
	unsigned char __t2ae : 1;
	unsigned char : 2;
	unsigned char __t2pf : 1;
	unsigned char __t2af : 1;
	unsigned char : 2;
} __mfi3_bits;

typedef union {
	__mfi3_bits bits;
	__sfr_byte byte;
} __mfi3_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char __pbpu7 : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char __pb7 : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char __pbc7 : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char __pcpu7 : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char __pc7 : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char __pcc7 : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char : 5;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char : 5;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char : 5;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char : 4;
	unsigned char __fsyson : 1;
} __ctrl_bits;

typedef union {
	__ctrl_bits bits;
	__sfr_byte byte;
} __ctrl_type;

typedef struct {
	unsigned char __vrefs : 1;
	unsigned char : 1;
	unsigned char __ador0 : 1;
	unsigned char __ador1 : 1;
	unsigned char __ador2 : 1;
	unsigned char __adoff : 1;
	unsigned char __adslp : 1;
	unsigned char __adrst : 1;
} __adcr0_bits;

typedef union {
	__adcr0_bits bits;
	__sfr_byte byte;
} __adcr0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __eoc : 1;
	unsigned char __adcdl : 1;
	unsigned char __vrbufp : 1;
	unsigned char __vrbufn : 1;
	unsigned char __flms0 : 1;
	unsigned char __flms1 : 1;
	unsigned char __flms2 : 1;
} __adcr1_bits;

typedef union {
	__adcr1_bits bits;
	__sfr_byte byte;
} __adcr1_type;

typedef struct {
	unsigned char __adck0 : 1;
	unsigned char __adck1 : 1;
	unsigned char __adck2 : 1;
	unsigned char __adck3 : 1;
	unsigned char __adck4 : 1;
	unsigned char : 3;
} __adcs_bits;

typedef union {
	__adcs_bits bits;
	__sfr_byte byte;
} __adcs_type;

typedef struct {
	unsigned char : 3;
	unsigned char __t1on : 1;
	unsigned char __t1ck0 : 1;
	unsigned char __t1ck1 : 1;
	unsigned char __t1ck2 : 1;
	unsigned char __t1pau : 1;
} __ptm1c0_bits;

typedef union {
	__ptm1c0_bits bits;
	__sfr_byte byte;
} __ptm1c0_type;

typedef struct {
	unsigned char __t1cclr : 1;
	unsigned char __t1capts : 1;
	unsigned char __t1pol : 1;
	unsigned char __t1oc : 1;
	unsigned char __t1io0 : 1;
	unsigned char __t1io1 : 1;
	unsigned char __t1m0 : 1;
	unsigned char __t1m1 : 1;
} __ptm1c1_bits;

typedef union {
	__ptm1c1_bits bits;
	__sfr_byte byte;
} __ptm1c1_type;

typedef struct {
	unsigned char __t0rp0 : 1;
	unsigned char __t0rp1 : 1;
	unsigned char __t0rp2 : 1;
	unsigned char __t0on : 1;
	unsigned char __t0ck0 : 1;
	unsigned char __t0ck1 : 1;
	unsigned char __t0ck2 : 1;
	unsigned char __t0pau : 1;
} __tm0c0_bits;

typedef union {
	__tm0c0_bits bits;
	__sfr_byte byte;
} __tm0c0_type;

typedef struct {
	unsigned char __t0cclr : 1;
	unsigned char __t0dpx : 1;
	unsigned char __t0pol : 1;
	unsigned char __t0oc : 1;
	unsigned char __t0io0 : 1;
	unsigned char __t0io1 : 1;
	unsigned char __t0m0 : 1;
	unsigned char __t0m1 : 1;
} __tm0c1_bits;

typedef union {
	__tm0c1_bits bits;
	__sfr_byte byte;
} __tm0c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __t2on : 1;
	unsigned char __t2ck0 : 1;
	unsigned char __t2ck1 : 1;
	unsigned char __t2ck2 : 1;
	unsigned char __t2pau : 1;
} __ptm2c0_bits;

typedef union {
	__ptm2c0_bits bits;
	__sfr_byte byte;
} __ptm2c0_type;

typedef struct {
	unsigned char __t2cclr : 1;
	unsigned char __t2capts : 1;
	unsigned char __t2pol : 1;
	unsigned char __t2oc : 1;
	unsigned char __t2io0 : 1;
	unsigned char __t2io1 : 1;
	unsigned char __t2m0 : 1;
	unsigned char __t2m1 : 1;
} __ptm2c1_bits;

typedef union {
	__ptm2c1_bits bits;
	__sfr_byte byte;
} __ptm2c1_type;

typedef struct {
	unsigned char __tp0cps : 1;
	unsigned char __tp1cps : 1;
	unsigned char __tp2cps : 1;
	unsigned char : 5;
} __ctrl0_bits;

typedef union {
	__ctrl0_bits bits;
	__sfr_byte byte;
} __ctrl0_type;

typedef struct {
	unsigned char __paps0 : 1;
	unsigned char __paps1 : 1;
	unsigned char __paps2 : 1;
	unsigned char __paps3 : 1;
	unsigned char __pbps0 : 1;
	unsigned char __pbps1 : 1;
	unsigned char __pbps2 : 1;
	unsigned char __pbps3 : 1;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __pcps0 : 1;
	unsigned char __pcps1 : 1;
	unsigned char __pcps2 : 1;
	unsigned char __pcps3 : 1;
	unsigned char __pdps0 : 1;
	unsigned char __pdps1 : 1;
	unsigned char : 2;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;

typedef struct {
	unsigned char __ldovs0 : 1;
	unsigned char __ldovs1 : 1;
	unsigned char __ldobps : 1;
	unsigned char : 3;
	unsigned char __envcm : 1;
	unsigned char __enldo : 1;
} __pwrc_bits;

typedef union {
	__pwrc_bits bits;
	__sfr_byte byte;
} __pwrc_type;

typedef struct {
	unsigned char __pgs0 : 1;
	unsigned char __pgs1 : 1;
	unsigned char __pgs2 : 1;
	unsigned char __ags0 : 1;
	unsigned char __ags1 : 1;
	unsigned char __vgs0 : 1;
	unsigned char __vgs1 : 1;
	unsigned char : 1;
} __pgac0_bits;

typedef union {
	__pgac0_bits bits;
	__sfr_byte byte;
} __pgac0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __dcset0 : 1;
	unsigned char __dcset1 : 1;
	unsigned char __dcset2 : 1;
	unsigned char : 2;
	unsigned char __inis : 1;
	unsigned char __vcms : 1;
} __pgac1_bits;

typedef union {
	__pgac1_bits bits;
	__sfr_byte byte;
} __pgac1_type;

typedef struct {
	unsigned char __chsp0 : 1;
	unsigned char __chsp1 : 1;
	unsigned char __chsp2 : 1;
	unsigned char __chsn0 : 1;
	unsigned char __chsn1 : 1;
	unsigned char __chsn2 : 1;
	unsigned char : 2;
} __pgacs_bits;

typedef union {
	__pgacs_bits bits;
	__sfr_byte byte;
} __pgacs_type;

typedef struct {
	unsigned char __txif : 1;
	unsigned char __tidle : 1;
	unsigned char __rxif : 1;
	unsigned char __ridle : 1;
	unsigned char __oerr : 1;
	unsigned char __ferr : 1;
	unsigned char __nf : 1;
	unsigned char __perr : 1;
} __usr_bits;

typedef union {
	__usr_bits bits;
	__sfr_byte byte;
} __usr_type;

typedef struct {
	unsigned char __tx8 : 1;
	unsigned char __rx8 : 1;
	unsigned char __txbrk : 1;
	unsigned char __stops : 1;
	unsigned char __prt : 1;
	unsigned char __pren : 1;
	unsigned char __bno : 1;
	unsigned char __uarten : 1;
} __ucr1_bits;

typedef union {
	__ucr1_bits bits;
	__sfr_byte byte;
} __ucr1_type;

typedef struct {
	unsigned char __teie : 1;
	unsigned char __tiie : 1;
	unsigned char __rie : 1;
	unsigned char __wake : 1;
	unsigned char __adden : 1;
	unsigned char __brgh : 1;
	unsigned char __rxen : 1;
	unsigned char __txen : 1;
} __ucr2_bits;

typedef union {
	__ucr2_bits bits;
	__sfr_byte byte;
} __ucr2_type;

typedef struct {
	unsigned char __brgd0 : 1;
	unsigned char __brgd1 : 1;
	unsigned char __brgd2 : 1;
	unsigned char __brgd3 : 1;
	unsigned char __brgd4 : 1;
	unsigned char __brgd5 : 1;
	unsigned char __brgd6 : 1;
	unsigned char __brgd7 : 1;
} __brg_bits;

typedef union {
	__brg_bits bits;
	__sfr_byte byte;
} __brg_type;

typedef struct {
	unsigned char __txrxd0 : 1;
	unsigned char __txrxd1 : 1;
	unsigned char __txrxd2 : 1;
	unsigned char __txrxd3 : 1;
	unsigned char __txrxd4 : 1;
	unsigned char __txrxd5 : 1;
	unsigned char __txrxd6 : 1;
	unsigned char __txrxd7 : 1;
} __txrrxr_bits;

typedef union {
	__txrrxr_bits bits;
	__sfr_byte byte;
} __txrrxr_type;

typedef struct {
	unsigned char __irdc0 : 1;
	unsigned char __irdc1 : 1;
	unsigned char __irdc2 : 1;
	unsigned char __irdc3 : 1;
	unsigned char __irdc4 : 1;
	unsigned char __irdc5 : 1;
	unsigned char __irdc6 : 1;
	unsigned char __irtc : 1;
} __irctrl0_bits;

typedef union {
	__irctrl0_bits bits;
	__sfr_byte byte;
} __irctrl0_type;

typedef struct {
	unsigned char __irme0 : 1;
	unsigned char : 7;
} __irctrl1_bits;

typedef union {
	__irctrl1_bits bits;
	__sfr_byte byte;
} __irctrl1_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdnc0 : 1;
	unsigned char __simdbc1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __rnic : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char __iica0 : 1;
	unsigned char __iica1 : 1;
	unsigned char __iica2 : 1;
	unsigned char __iica3 : 1;
	unsigned char __iica4 : 1;
	unsigned char __iica5 : 1;
	unsigned char __iica6 : 1;
	unsigned char : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __a0 : 1;
	unsigned char __a1 : 1;
	unsigned char __a2 : 1;
	unsigned char __a3 : 1;
	unsigned char __a4 : 1;
	unsigned char __a5 : 1;
	unsigned char __a6 : 1;
	unsigned char __a7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __a8 : 1;
	unsigned char __a9 : 1;
	unsigned char __a10 : 1;
	unsigned char __a11 : 1;
	unsigned char __a12 : 1;
	unsigned char __a13 : 1;
	unsigned char __a14 : 1;
	unsigned char __a15 : 1;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char : 4;
	unsigned char __bren : 1;
	unsigned char : 2;
	unsigned char __sgen : 1;
} __sgc_bits;

typedef union {
	__sgc_bits bits;
	__sfr_byte byte;
} __sgc_type;

typedef struct {
	unsigned char __op2g0 : 1;
	unsigned char __op2g1 : 1;
	unsigned char __op2g2 : 1;
	unsigned char __op2g3 : 1;
	unsigned char : 3;
	unsigned char __opaen : 1;
} __opac_bits;

typedef union {
	__opac_bits bits;
	__sfr_byte byte;
} __opac_type;

typedef struct {
	unsigned char __sw0 : 1;
	unsigned char __sw1 : 1;
	unsigned char __sw2 : 1;
	unsigned char __sw3 : 1;
	unsigned char __sw4 : 1;
	unsigned char __sw5 : 1;
	unsigned char __sw6 : 1;
	unsigned char __sw7 : 1;
} __swc_bits;

typedef union {
	__swc_bits bits;
	__sfr_byte byte;
} __swc_type;

typedef struct {
	unsigned char __sw8 : 1;
	unsigned char __sw9 : 1;
	unsigned char : 2;
	unsigned char __hysen : 1;
	unsigned char : 2;
	unsigned char __ftren : 1;
} __ftrc_bits;

typedef union {
	__ftrc_bits bits;
	__sfr_byte byte;
} __ftrc_type;

typedef struct {
	unsigned char __hlclk : 1;
	unsigned char __idlen : 1;
	unsigned char __hto : 1;
	unsigned char __lto : 1;
	unsigned char __fsten : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __smod_bits;

typedef union {
	__smod_bits bits;
	__sfr_byte byte;
} __smod_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char : 4;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char __lxtlp : 1;
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tbck : 1;
	unsigned char __tbon : 1;
} __tbc_bits;

typedef union {
	__tbc_bits bits;
	__sfr_byte byte;
} __tbc_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;


DEFINE_SFR(__mp0_type, __mp0, 0x01);
DEFINE_SFR(__mp1l_type, __mp1l, 0x03);
DEFINE_SFR(__mp1h_type, __mp1h, 0x04);
DEFINE_SFR(__acc_type, __acc, 0x05);
DEFINE_SFR(__pcl_type, __pcl, 0x06);
DEFINE_SFR(__tblp_type, __tblp, 0x07);
DEFINE_SFR(__tblh_type, __tblh, 0x08);
DEFINE_SFR(__tbhp_type, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__mp2l_type, __mp2l, 0x0d);
DEFINE_SFR(__mp2h_type, __mp2h, 0x0e);
DEFINE_SFR(__intc0_type, __intc0, 0x10);
DEFINE_SFR(__intc1_type, __intc1, 0x11);
DEFINE_SFR(__intc2_type, __intc2, 0x12);
DEFINE_SFR(__mfi0_type, __mfi0, 0x14);
DEFINE_SFR(__mfi1_type, __mfi1, 0x15);
DEFINE_SFR(__mfi2_type, __mfi2, 0x16);
DEFINE_SFR(__mfi3_type, __mfi3, 0x17);
DEFINE_SFR(__pawu_type, __pawu, 0x18);
DEFINE_SFR(__papu_type, __papu, 0x19);
DEFINE_SFR(__pa_type, __pa, 0x1a);
DEFINE_SFR(__pac_type, __pac, 0x1b);
DEFINE_SFR(__pbpu_type, __pbpu, 0x1c);
DEFINE_SFR(__pb_type, __pb, 0x1d);
DEFINE_SFR(__pbc_type, __pbc, 0x1e);
DEFINE_SFR(__pcpu_type, __pcpu, 0x1f);
DEFINE_SFR(__pc_type, __pc, 0x20);
DEFINE_SFR(__pcc_type, __pcc, 0x21);
DEFINE_SFR(__pdpu_type, __pdpu, 0x22);
DEFINE_SFR(__pd_type, __pd, 0x23);
DEFINE_SFR(__pdc_type, __pdc, 0x24);
DEFINE_SFR(__lvrc_type, __lvrc, 0x2b);
DEFINE_SFR(__ctrl_type, __ctrl, 0x2c);
DEFINE_SFR(__sfr_byte, __adrl, 0x2e);
DEFINE_SFR(__sfr_byte, __adrh, 0x2f);
DEFINE_SFR(__adcr0_type, __adcr0, 0x30);
DEFINE_SFR(__adcr1_type, __adcr1, 0x31);
DEFINE_SFR(__adcs_type, __adcs, 0x32);
DEFINE_SFR(__sfr_byte, __adrm, 0x33);
DEFINE_SFR(__ptm1c0_type, __ptm1c0, 0x34);
DEFINE_SFR(__ptm1c1_type, __ptm1c1, 0x35);
DEFINE_SFR(__sfr_byte, __ptm1dl, 0x36);
DEFINE_SFR(__sfr_byte, __ptm1dh, 0x37);
DEFINE_SFR(__sfr_byte, __ptm1al, 0x38);
DEFINE_SFR(__sfr_byte, __ptm1ah, 0x39);
DEFINE_SFR(__tm0c0_type, __tm0c0, 0x3a);
DEFINE_SFR(__tm0c1_type, __tm0c1, 0x3b);
DEFINE_SFR(__sfr_byte, __tm0dl, 0x3c);
DEFINE_SFR(__sfr_byte, __tm0dh, 0x3d);
DEFINE_SFR(__sfr_byte, __tm0al, 0x3e);
DEFINE_SFR(__sfr_byte, __tm0ah, 0x3f);
DEFINE_SFR(__sfr_byte, __eea, 0x41);
DEFINE_SFR(__sfr_byte, __eed, 0x42);
DEFINE_SFR(__ptm2c0_type, __ptm2c0, 0x43);
DEFINE_SFR(__ptm2c1_type, __ptm2c1, 0x44);
DEFINE_SFR(__sfr_byte, __ptm2dl, 0x45);
DEFINE_SFR(__sfr_byte, __ptm2dh, 0x46);
DEFINE_SFR(__sfr_byte, __ptm2al, 0x47);
DEFINE_SFR(__sfr_byte, __ptm2ah, 0x48);
DEFINE_SFR(__ctrl0_type, __ctrl0, 0x49);
DEFINE_SFR(__sfr_byte, __ptm1rpl, 0x4a);
DEFINE_SFR(__sfr_byte, __ptm1rph, 0x4b);
DEFINE_SFR(__sfr_byte, __ptm2rpl, 0x4c);
DEFINE_SFR(__sfr_byte, __ptm2rph, 0x4d);
DEFINE_SFR(__sledc0_type, __sledc0, 0x4e);
DEFINE_SFR(__sledc1_type, __sledc1, 0x4f);
DEFINE_SFR(__pwrc_type, __pwrc, 0x50);
DEFINE_SFR(__pgac0_type, __pgac0, 0x51);
DEFINE_SFR(__pgac1_type, __pgac1, 0x52);
DEFINE_SFR(__pgacs_type, __pgacs, 0x53);
DEFINE_SFR(__usr_type, __usr, 0x54);
DEFINE_SFR(__ucr1_type, __ucr1, 0x55);
DEFINE_SFR(__ucr2_type, __ucr2, 0x56);
DEFINE_SFR(__brg_type, __brg, 0x57);
DEFINE_SFR(__txrrxr_type, __txrrxr, 0x58);
DEFINE_SFR(__irctrl0_type, __irctrl0, 0x59);
DEFINE_SFR(__irctrl1_type, __irctrl1, 0x5a);
DEFINE_SFR(__simc0_type, __simc0, 0x60);
DEFINE_SFR(__simc1_type, __simc1, 0x61);
DEFINE_SFR(__simc2_type, __simc2, 0x62);
DEFINE_SFR(__sima_type, __sima, 0x62);
DEFINE_SFR(__sfr_byte, __simd, 0x63);
DEFINE_SFR(__simtoc_type, __simtoc, 0x65);
DEFINE_SFR(__farl_type, __farl, 0x66);
DEFINE_SFR(__farh_type, __farh, 0x67);
DEFINE_SFR(__sfr_byte, __fd0l, 0x68);
DEFINE_SFR(__sfr_byte, __fd0h, 0x69);
DEFINE_SFR(__sfr_byte, __fd1l, 0x6a);
DEFINE_SFR(__sfr_byte, __fd1h, 0x6b);
DEFINE_SFR(__sfr_byte, __fd2l, 0x6c);
DEFINE_SFR(__sfr_byte, __fd2h, 0x6d);
DEFINE_SFR(__sfr_byte, __fd3l, 0x6e);
DEFINE_SFR(__sfr_byte, __fd3h, 0x6f);
DEFINE_SFR(__sgc_type, __sgc, 0x70);
DEFINE_SFR(__sfr_byte, __sgn, 0x71);
DEFINE_SFR(__sfr_byte, __sgdnr, 0x72);
DEFINE_SFR(__opac_type, __opac, 0x73);
DEFINE_SFR(__swc_type, __swc, 0x74);
DEFINE_SFR(__sfr_byte, __daco, 0x75);
DEFINE_SFR(__ftrc_type, __ftrc, 0x76);
DEFINE_SFR(__smod_type, __smod, 0x77);
DEFINE_SFR(__lvdc_type, __lvdc, 0x78);
DEFINE_SFR(__integ_type, __integ, 0x79);
DEFINE_SFR(__wdtc_type, __wdtc, 0x7a);
DEFINE_SFR(__tbc_type, __tbc, 0x7b);
DEFINE_SFR(__fc0_type, __fc0, 0x128);
DEFINE_SFR(__sfr_byte, __fc1, 0x129);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0.byte
#define _mp1l     __mp1l.byte
#define _mp1h     __mp1h.byte
#define _acc      __acc.byte
#define _pcl      __pcl.byte
#define _tblp     __tblp.byte
#define _tblh     __tblh.byte
#define _tbhp     __tbhp.byte
#define _status   __status.byte
#define _mp2l     __mp2l.byte
#define _mp2h     __mp2h.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _mfi3     __mfi3.byte
#define _pawu     __pawu.byte
#define _papu     __papu.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _pbpu     __pbpu.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pcpu     __pcpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pdpu     __pdpu.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _lvrc     __lvrc.byte
#define _ctrl     __ctrl.byte
#define _adrl     __adrl
#define _adrh     __adrh
#define _adcr0    __adcr0.byte
#define _adcr1    __adcr1.byte
#define _adcs     __adcs.byte
#define _adrm     __adrm
#define _ptm1c0   __ptm1c0.byte
#define _ptm1c1   __ptm1c1.byte
#define _ptm1dl   __ptm1dl
#define _ptm1dh   __ptm1dh
#define _ptm1al   __ptm1al
#define _ptm1ah   __ptm1ah
#define _tm0c0    __tm0c0.byte
#define _tm0c1    __tm0c1.byte
#define _tm0dl    __tm0dl
#define _tm0dh    __tm0dh
#define _tm0al    __tm0al
#define _tm0ah    __tm0ah
#define _eea      __eea
#define _eed      __eed
#define _ptm2c0   __ptm2c0.byte
#define _ptm2c1   __ptm2c1.byte
#define _ptm2dl   __ptm2dl
#define _ptm2dh   __ptm2dh
#define _ptm2al   __ptm2al
#define _ptm2ah   __ptm2ah
#define _ctrl0    __ctrl0.byte
#define _ptm1rpl  __ptm1rpl
#define _ptm1rph  __ptm1rph
#define _ptm2rpl  __ptm2rpl
#define _ptm2rph  __ptm2rph
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte
#define _pwrc     __pwrc.byte
#define _pgac0    __pgac0.byte
#define _pgac1    __pgac1.byte
#define _pgacs    __pgacs.byte
#define _usr      __usr.byte
#define _ucr1     __ucr1.byte
#define _ucr2     __ucr2.byte
#define _brg      __brg.byte
#define _txrrxr   __txrrxr.byte
#define _irctrl0  __irctrl0.byte
#define _irctrl1  __irctrl1.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simc2    __simc2.byte
#define _sima     __sima.byte
#define _simd     __simd
#define _simtoc   __simtoc.byte
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _sgc      __sgc.byte
#define _sgn      __sgn
#define _sgdnr    __sgdnr
#define _opac     __opac.byte
#define _swc      __swc.byte
#define _daco     __daco
#define _ftrc     __ftrc.byte
#define _smod     __smod.byte
#define _lvdc     __lvdc.byte
#define _integ    __integ.byte
#define _wdtc     __wdtc.byte
#define _tbc      __tbc.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _eec      __eec.byte

#define _mp00     __mp0.bits.__mp00
#define _mp01     __mp0.bits.__mp01
#define _mp02     __mp0.bits.__mp02
#define _mp03     __mp0.bits.__mp03
#define _mp04     __mp0.bits.__mp04
#define _mp05     __mp0.bits.__mp05
#define _mp06     __mp0.bits.__mp06
#define _mp07     __mp0.bits.__mp07
#define _mp1l0    __mp1l.bits.__mp1l0
#define _mp1l1    __mp1l.bits.__mp1l1
#define _mp1l2    __mp1l.bits.__mp1l2
#define _mp1l3    __mp1l.bits.__mp1l3
#define _mp1l4    __mp1l.bits.__mp1l4
#define _mp1l5    __mp1l.bits.__mp1l5
#define _mp1l6    __mp1l.bits.__mp1l6
#define _mp1l7    __mp1l.bits.__mp1l7
#define _mp1h0    __mp1h.bits.__mp1h0
#define _mp1h1    __mp1h.bits.__mp1h1
#define _mp1h2    __mp1h.bits.__mp1h2
#define _mp1h3    __mp1h.bits.__mp1h3
#define _mp1h4    __mp1h.bits.__mp1h4
#define _mp1h5    __mp1h.bits.__mp1h5
#define _mp1h6    __mp1h.bits.__mp1h6
#define _mp1h7    __mp1h.bits.__mp1h7
#define _acc0     __acc.bits.__acc0
#define _acc1     __acc.bits.__acc1
#define _acc2     __acc.bits.__acc2
#define _acc3     __acc.bits.__acc3
#define _acc4     __acc.bits.__acc4
#define _acc5     __acc.bits.__acc5
#define _acc6     __acc.bits.__acc6
#define _acc7     __acc.bits.__acc7
#define _pcl0     __pcl.bits.__pcl0
#define _pcl1     __pcl.bits.__pcl1
#define _pcl2     __pcl.bits.__pcl2
#define _pcl3     __pcl.bits.__pcl3
#define _pcl4     __pcl.bits.__pcl4
#define _pcl5     __pcl.bits.__pcl5
#define _pcl6     __pcl.bits.__pcl6
#define _pcl7     __pcl.bits.__pcl7
#define _tblp0    __tblp.bits.__tblp0
#define _tblp1    __tblp.bits.__tblp1
#define _tblp2    __tblp.bits.__tblp2
#define _tblp3    __tblp.bits.__tblp3
#define _tblp4    __tblp.bits.__tblp4
#define _tblp5    __tblp.bits.__tblp5
#define _tblp6    __tblp.bits.__tblp6
#define _tblp7    __tblp.bits.__tblp7
#define _tblh0    __tblh.bits.__tblh0
#define _tblh1    __tblh.bits.__tblh1
#define _tblh2    __tblh.bits.__tblh2
#define _tblh3    __tblh.bits.__tblh3
#define _tblh4    __tblh.bits.__tblh4
#define _tblh5    __tblh.bits.__tblh5
#define _tblh6    __tblh.bits.__tblh6
#define _tblh7    __tblh.bits.__tblh7
#define _tbhp0    __tbhp.bits.__tbhp0
#define _tbhp1    __tbhp.bits.__tbhp1
#define _tbhp2    __tbhp.bits.__tbhp2
#define _tbhp3    __tbhp.bits.__tbhp3
#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _mp2l0    __mp2l.bits.__mp2l0
#define _mp2l1    __mp2l.bits.__mp2l1
#define _mp2l2    __mp2l.bits.__mp2l2
#define _mp2l3    __mp2l.bits.__mp2l3
#define _mp2l4    __mp2l.bits.__mp2l4
#define _mp2l5    __mp2l.bits.__mp2l5
#define _mp2l6    __mp2l.bits.__mp2l6
#define _mp2l7    __mp2l.bits.__mp2l7
#define _mp2h0    __mp2h.bits.__mp2h0
#define _mp2h1    __mp2h.bits.__mp2h1
#define _mp2h2    __mp2h.bits.__mp2h2
#define _mp2h3    __mp2h.bits.__mp2h3
#define _mp2h4    __mp2h.bits.__mp2h4
#define _mp2h5    __mp2h.bits.__mp2h5
#define _mp2h6    __mp2h.bits.__mp2h6
#define _mp2h7    __mp2h.bits.__mp2h7
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _mf0e     __intc0.bits.__mf0e
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _mf0f     __intc0.bits.__mf0f
#define _ade      __intc1.bits.__ade
#define _tb0e     __intc1.bits.__tb0e
#define _tb1e     __intc1.bits.__tb1e
#define _mf1e     __intc1.bits.__mf1e
#define _adf      __intc1.bits.__adf
#define _tb0f     __intc1.bits.__tb0f
#define _tb1f     __intc1.bits.__tb1f
#define _mf1f     __intc1.bits.__mf1f
#define _mf2e     __intc2.bits.__mf2e
#define _mf3e     __intc2.bits.__mf3e
#define _mf2f     __intc2.bits.__mf2f
#define _mf3f     __intc2.bits.__mf3f
#define _t0pe     __mfi0.bits.__t0pe
#define _t0ae     __mfi0.bits.__t0ae
#define _t0pf     __mfi0.bits.__t0pf
#define _t0af     __mfi0.bits.__t0af
#define _lve      __mfi1.bits.__lve
#define _dee      __mfi1.bits.__dee
#define _sie      __mfi1.bits.__sie
#define _uie      __mfi1.bits.__uie
#define _lvf      __mfi1.bits.__lvf
#define _def      __mfi1.bits.__def
#define _sif      __mfi1.bits.__sif
#define _uif      __mfi1.bits.__uif
#define _t1pe     __mfi2.bits.__t1pe
#define _t1ae     __mfi2.bits.__t1ae
#define _i2ctoi   __mfi2.bits.__i2ctoi
#define _t1pf     __mfi2.bits.__t1pf
#define _t1af     __mfi2.bits.__t1af
#define _i2ctof   __mfi2.bits.__i2ctof
#define _t2pe     __mfi3.bits.__t2pe
#define _t2ae     __mfi3.bits.__t2ae
#define _t2pf     __mfi3.bits.__t2pf
#define _t2af     __mfi3.bits.__t2af
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _pbpu7    __pbpu.bits.__pbpu7
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pb7      __pb.bits.__pb7
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbc7     __pbc.bits.__pbc7
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _pcpu7    __pcpu.bits.__pcpu7
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pc7      __pc.bits.__pc7
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcc7     __pcc.bits.__pcc7
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _wrf      __ctrl.bits.__wrf
#define _lrf      __ctrl.bits.__lrf
#define _lvrf     __ctrl.bits.__lvrf
#define _fsyson   __ctrl.bits.__fsyson
#define _vrefs    __adcr0.bits.__vrefs
#define _ador0    __adcr0.bits.__ador0
#define _ador1    __adcr0.bits.__ador1
#define _ador2    __adcr0.bits.__ador2
#define _adoff    __adcr0.bits.__adoff
#define _adslp    __adcr0.bits.__adslp
#define _adrst    __adcr0.bits.__adrst
#define _eoc      __adcr1.bits.__eoc
#define _adcdl    __adcr1.bits.__adcdl
#define _vrbufp   __adcr1.bits.__vrbufp
#define _vrbufn   __adcr1.bits.__vrbufn
#define _flms0    __adcr1.bits.__flms0
#define _flms1    __adcr1.bits.__flms1
#define _flms2    __adcr1.bits.__flms2
#define _adck0    __adcs.bits.__adck0
#define _adck1    __adcs.bits.__adck1
#define _adck2    __adcs.bits.__adck2
#define _adck3    __adcs.bits.__adck3
#define _adck4    __adcs.bits.__adck4
#define _t1on     __ptm1c0.bits.__t1on
#define _t1ck0    __ptm1c0.bits.__t1ck0
#define _t1ck1    __ptm1c0.bits.__t1ck1
#define _t1ck2    __ptm1c0.bits.__t1ck2
#define _t1pau    __ptm1c0.bits.__t1pau
#define _t1cclr   __ptm1c1.bits.__t1cclr
#define _t1capts  __ptm1c1.bits.__t1capts
#define _t1pol    __ptm1c1.bits.__t1pol
#define _t1oc     __ptm1c1.bits.__t1oc
#define _t1io0    __ptm1c1.bits.__t1io0
#define _t1io1    __ptm1c1.bits.__t1io1
#define _t1m0     __ptm1c1.bits.__t1m0
#define _t1m1     __ptm1c1.bits.__t1m1
#define _t0rp0    __tm0c0.bits.__t0rp0
#define _t0rp1    __tm0c0.bits.__t0rp1
#define _t0rp2    __tm0c0.bits.__t0rp2
#define _t0on     __tm0c0.bits.__t0on
#define _t0ck0    __tm0c0.bits.__t0ck0
#define _t0ck1    __tm0c0.bits.__t0ck1
#define _t0ck2    __tm0c0.bits.__t0ck2
#define _t0pau    __tm0c0.bits.__t0pau
#define _t0cclr   __tm0c1.bits.__t0cclr
#define _t0dpx    __tm0c1.bits.__t0dpx
#define _t0pol    __tm0c1.bits.__t0pol
#define _t0oc     __tm0c1.bits.__t0oc
#define _t0io0    __tm0c1.bits.__t0io0
#define _t0io1    __tm0c1.bits.__t0io1
#define _t0m0     __tm0c1.bits.__t0m0
#define _t0m1     __tm0c1.bits.__t0m1
#define _t2on     __ptm2c0.bits.__t2on
#define _t2ck0    __ptm2c0.bits.__t2ck0
#define _t2ck1    __ptm2c0.bits.__t2ck1
#define _t2ck2    __ptm2c0.bits.__t2ck2
#define _t2pau    __ptm2c0.bits.__t2pau
#define _t2cclr   __ptm2c1.bits.__t2cclr
#define _t2capts  __ptm2c1.bits.__t2capts
#define _t2pol    __ptm2c1.bits.__t2pol
#define _t2oc     __ptm2c1.bits.__t2oc
#define _t2io0    __ptm2c1.bits.__t2io0
#define _t2io1    __ptm2c1.bits.__t2io1
#define _t2m0     __ptm2c1.bits.__t2m0
#define _t2m1     __ptm2c1.bits.__t2m1
#define _tp0cps   __ctrl0.bits.__tp0cps
#define _tp1cps   __ctrl0.bits.__tp1cps
#define _tp2cps   __ctrl0.bits.__tp2cps
#define _paps0    __sledc0.bits.__paps0
#define _paps1    __sledc0.bits.__paps1
#define _paps2    __sledc0.bits.__paps2
#define _paps3    __sledc0.bits.__paps3
#define _pbps0    __sledc0.bits.__pbps0
#define _pbps1    __sledc0.bits.__pbps1
#define _pbps2    __sledc0.bits.__pbps2
#define _pbps3    __sledc0.bits.__pbps3
#define _pcps0    __sledc1.bits.__pcps0
#define _pcps1    __sledc1.bits.__pcps1
#define _pcps2    __sledc1.bits.__pcps2
#define _pcps3    __sledc1.bits.__pcps3
#define _pdps0    __sledc1.bits.__pdps0
#define _pdps1    __sledc1.bits.__pdps1
#define _ldovs0   __pwrc.bits.__ldovs0
#define _ldovs1   __pwrc.bits.__ldovs1
#define _ldobps   __pwrc.bits.__ldobps
#define _envcm    __pwrc.bits.__envcm
#define _enldo    __pwrc.bits.__enldo
#define _pgs0     __pgac0.bits.__pgs0
#define _pgs1     __pgac0.bits.__pgs1
#define _pgs2     __pgac0.bits.__pgs2
#define _ags0     __pgac0.bits.__ags0
#define _ags1     __pgac0.bits.__ags1
#define _vgs0     __pgac0.bits.__vgs0
#define _vgs1     __pgac0.bits.__vgs1
#define _dcset0   __pgac1.bits.__dcset0
#define _dcset1   __pgac1.bits.__dcset1
#define _dcset2   __pgac1.bits.__dcset2
#define _inis     __pgac1.bits.__inis
#define _vcms     __pgac1.bits.__vcms
#define _chsp0    __pgacs.bits.__chsp0
#define _chsp1    __pgacs.bits.__chsp1
#define _chsp2    __pgacs.bits.__chsp2
#define _chsn0    __pgacs.bits.__chsn0
#define _chsn1    __pgacs.bits.__chsn1
#define _chsn2    __pgacs.bits.__chsn2
#define _txif     __usr.bits.__txif
#define _tidle    __usr.bits.__tidle
#define _rxif     __usr.bits.__rxif
#define _ridle    __usr.bits.__ridle
#define _oerr     __usr.bits.__oerr
#define _ferr     __usr.bits.__ferr
#define _nf       __usr.bits.__nf
#define _perr     __usr.bits.__perr
#define _tx8      __ucr1.bits.__tx8
#define _rx8      __ucr1.bits.__rx8
#define _txbrk    __ucr1.bits.__txbrk
#define _stops    __ucr1.bits.__stops
#define _prt      __ucr1.bits.__prt
#define _pren     __ucr1.bits.__pren
#define _bno      __ucr1.bits.__bno
#define _uarten   __ucr1.bits.__uarten
#define _teie     __ucr2.bits.__teie
#define _tiie     __ucr2.bits.__tiie
#define _rie      __ucr2.bits.__rie
#define _wake     __ucr2.bits.__wake
#define _adden    __ucr2.bits.__adden
#define _brgh     __ucr2.bits.__brgh
#define _rxen     __ucr2.bits.__rxen
#define _txen     __ucr2.bits.__txen
#define _brgd0    __brg.bits.__brgd0
#define _brgd1    __brg.bits.__brgd1
#define _brgd2    __brg.bits.__brgd2
#define _brgd3    __brg.bits.__brgd3
#define _brgd4    __brg.bits.__brgd4
#define _brgd5    __brg.bits.__brgd5
#define _brgd6    __brg.bits.__brgd6
#define _brgd7    __brg.bits.__brgd7
#define _txrxd0   __txrrxr.bits.__txrxd0
#define _txrxd1   __txrrxr.bits.__txrxd1
#define _txrxd2   __txrrxr.bits.__txrxd2
#define _txrxd3   __txrrxr.bits.__txrxd3
#define _txrxd4   __txrrxr.bits.__txrxd4
#define _txrxd5   __txrrxr.bits.__txrxd5
#define _txrxd6   __txrrxr.bits.__txrxd6
#define _txrxd7   __txrrxr.bits.__txrxd7
#define _irdc0    __irctrl0.bits.__irdc0
#define _irdc1    __irctrl0.bits.__irdc1
#define _irdc2    __irctrl0.bits.__irdc2
#define _irdc3    __irctrl0.bits.__irdc3
#define _irdc4    __irctrl0.bits.__irdc4
#define _irdc5    __irctrl0.bits.__irdc5
#define _irdc6    __irctrl0.bits.__irdc6
#define _irtc     __irctrl0.bits.__irtc
#define _irme0    __irctrl1.bits.__irme0
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdnc0  __simc0.bits.__simdnc0
#define _simdbc1  __simc0.bits.__simdbc1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _rnic     __simc1.bits.__rnic
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _iica0    __sima.bits.__iica0
#define _iica1    __sima.bits.__iica1
#define _iica2    __sima.bits.__iica2
#define _iica3    __sima.bits.__iica3
#define _iica4    __sima.bits.__iica4
#define _iica5    __sima.bits.__iica5
#define _iica6    __sima.bits.__iica6
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _a0       __farl.bits.__a0
#define _a1       __farl.bits.__a1
#define _a2       __farl.bits.__a2
#define _a3       __farl.bits.__a3
#define _a4       __farl.bits.__a4
#define _a5       __farl.bits.__a5
#define _a6       __farl.bits.__a6
#define _a7       __farl.bits.__a7
#define _a8       __farh.bits.__a8
#define _a9       __farh.bits.__a9
#define _a10      __farh.bits.__a10
#define _a11      __farh.bits.__a11
#define _a12      __farh.bits.__a12
#define _a13      __farh.bits.__a13
#define _a14      __farh.bits.__a14
#define _a15      __farh.bits.__a15
#define _bren     __sgc.bits.__bren
#define _sgen     __sgc.bits.__sgen
#define _op2g0    __opac.bits.__op2g0
#define _op2g1    __opac.bits.__op2g1
#define _op2g2    __opac.bits.__op2g2
#define _op2g3    __opac.bits.__op2g3
#define _opaen    __opac.bits.__opaen
#define _sw0      __swc.bits.__sw0
#define _sw1      __swc.bits.__sw1
#define _sw2      __swc.bits.__sw2
#define _sw3      __swc.bits.__sw3
#define _sw4      __swc.bits.__sw4
#define _sw5      __swc.bits.__sw5
#define _sw6      __swc.bits.__sw6
#define _sw7      __swc.bits.__sw7
#define _sw8      __ftrc.bits.__sw8
#define _sw9      __ftrc.bits.__sw9
#define _hysen    __ftrc.bits.__hysen
#define _ftren    __ftrc.bits.__ftren
#define _hlclk    __smod.bits.__hlclk
#define _idlen    __smod.bits.__idlen
#define _hto      __smod.bits.__hto
#define _lto      __smod.bits.__lto
#define _fsten    __smod.bits.__fsten
#define _cks0     __smod.bits.__cks0
#define _cks1     __smod.bits.__cks1
#define _cks2     __smod.bits.__cks2
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _tb00     __tbc.bits.__tb00
#define _tb01     __tbc.bits.__tb01
#define _tb02     __tbc.bits.__tb02
#define _lxtlp    __tbc.bits.__lxtlp
#define _tb10     __tbc.bits.__tb10
#define _tb11     __tbc.bits.__tb11
#define _tbck     __tbc.bits.__tbck
#define _tbon     __tbc.bits.__tbon
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _HT45F75_H_
